# Generated by Django 2.2.6 on 2019-11-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20191112_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='followers',
            field=models.ManyToManyField(blank=True, default=None, related_name='_userprofile_followers_+', to='backend.UserProfile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='following',
            field=models.ManyToManyField(blank=True, default=None, related_name='_userprofile_following_+', to='backend.UserProfile'),
        ),
    ]
