# Generated by Django 2.2.6 on 2019-11-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20191113_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='like_comments',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='like_posts',
            field=models.ManyToManyField(blank=True, related_name='likes_post', to='backend.Post'),
        ),
    ]
